name: Push docs
on:
  push:
    branches: [ "main" ]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Push doc folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'doc'
        destination_repo: 'doumor/mkdocs-publish'
        destination_folder: 'docs/linux_onboarding'
        user_email: 'doumor@vk.com'
        user_name: 'doumor'
        commit_msg: 'Update the linux_onboarding docs files.'
        destination_branch: 'main'
